mosp/models/collection.py
import uuid
from datetime import datetime

from sqlalchemy.dialects.postgresql import UUID

from mosp.bootstrap import db


class Collection(db.Model):
    """Represent a collection."""

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(
        UUID(as_uuid=True),
        default=uuid.uuid4,
        unique=True,
        nullable=False,
    )
    name = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.String(500), default="")
    date_created = db.Column(db.DateTime(), default=datetime.utcnow)
    last_updated = db.Column(db.DateTime(), default=datetime.utcnow)

    # foreign keys
    creator_id = db.Column(db.Integer(), db.ForeignKey("user.id"), nullable=False)

    def __str__(self):
        return self.name

mosp/models/organization.py
from datetime import datetime

from mosp.bootstrap import db


class Organization(db.Model):
    """Represent an organization."""

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(500), default="")
    organization_type = db.Column(db.String(100), default="")
    website = db.Column(db.String(100), default="")
    last_updated = db.Column(db.DateTime(), default=datetime.utcnow)

    is_membership_restricted = db.Column(db.Boolean(), default=True)

    # relationship
    objects = db.relationship(
        "JsonObject",
        backref="organization",
        lazy="dynamic",
        cascade="all,delete-orphan",
    )
    schemas = db.relationship(
        "Schema", backref="organization", lazy="dynamic", cascade="all,delete-orphan"
    )

    def __str__(self):
        return self.name

    def __eq__(self, obj):
        return self.id == obj.id

mosp/views/organization.py
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_paginate import get_page_args
from flask_paginate import Pagination
from sqlalchemy import desc
from sqlalchemy import func
from sqlalchemy import nullslast
from sqlalchemy import or_

from mosp.bootstrap import db
from mosp.models import JsonObject
from mosp.models import Organization
from mosp.models import Schema

organization_bp = Blueprint("organization_bp", __name__, url_prefix="/organization")
organizations_bp = Blueprint("organizations_bp", __name__, url_prefix="/organizations")


@organizations_bp.route("/", methods=["GET"])
def list_organizations():
    """Return the page which will display the list of organizations."""
    # Order by organization wich provides the most JSON objects.
    is_membership_restricted = int(request.args.get("is_membership_restricted", 1)) == 1
    big_contributors = (
        db.session.query(JsonObject.org_id, func.count("*").label("JsonObject_count"))
        .group_by(JsonObject.org_id)
        .subquery()
    )
    if not is_membership_restricted:
        organizations = (
            db.session.query(Organization)
            .filter(Organization.is_membership_restricted == False)  # noqa
            .outerjoin(big_contributors, (Organization.id == big_contributors.c.org_id))
            .order_by(nullslast(desc(big_contributors.c.JsonObject_count)))
        )
    else:
        organizations = (
            db.session.query(Organization)
            .outerjoin(big_contributors, (Organization.id == big_contributors.c.org_id))
            .order_by(nullslast(desc(big_contributors.c.JsonObject_count)))
        )
    return render_template("organizations.html", organizations=organizations)


@organization_bp.route(
    "/<int:organization_id>",
    defaults={"per_page_objects": "10", "per_page_schemas": "10"},
    methods=["GET"],
)
@organization_bp.route(
    "/<string:organization_name>",
    defaults={"per_page_objects": "10", "per_page_schemas": "10"},
    methods=["GET"],
)
def get(
    per_page_objects, per_page_schemas, organization_id=None, organization_name=None
):
    """Return details about the organization."""
    org = Organization.query.filter(
        or_(Organization.id == organization_id, Organization.name == organization_name)
    ).first()
    if org is None:
        abort(404)

    # Pagination on objects created by the organization
    query_objects = JsonObject.query.filter(JsonObject.org_id == org.id)
    page_objects, per_page_objects, offset_objects = get_page_args(
        page_parameter="page_objects", per_page_parameter="per_page_objects"
    )
    pagination_objects = Pagination(
        page_parameter="page_objects",
        page=page_objects,
        per_page=per_page_objects,
        total=query_objects.count(),
        css_framework="bootstrap4",
        search=False,
    )
    # Pagination on schemas created by the organization
    query_schemas = Schema.query.filter(Schema.org_id == org.id)
    page_schemas, per_page_schemas, offset_schemas = get_page_args(
        page_parameter="page_schemas", per_page_parameter="per_page_schemas"
    )
    pagination_schemas = Pagination(
        page_parameter="page_schemas",
        page=page_schemas,
        per_page=per_page_schemas,
        total=query_schemas.count(),
        css_framework="bootstrap4",
        search=False,
    )

    return render_template(
        "organization.html",
        organization=org,
        pagination_objects=pagination_objects,
        pagination_schemas=pagination_schemas,
        objects=query_objects.offset(offset_objects).limit(per_page_objects),
        schemas=query_schemas.offset(offset_schemas).limit(per_page_schemas),
    )


@organization_bp.route("/join/<org_id>", methods=["GET"])
@login_required
def join(org_id):
    """Let an authenticated user join an organization which has no membership restriction."""
    org = (
        Organization.query.filter(
            Organization.is_membership_restricted == False  # noqa
        )
        .filter(Organization.id == org_id)
        .first()
    )
    if org:
        current_user.organizations.append(org)
        db.session.commit()
        flash("You have successfully joined the organization.", "success")
    else:
        flash("You can not join this organization.", "warning")
    return redirect(url_for("organization_bp.get", organization_id=org_id))


@organization_bp.route("/leave/<org_id>", methods=["GET"])
@login_required
def leave(org_id):
    """Let an authenticated user leave an organization."""
    org = Organization.query.filter(Organization.id == org_id).first()
    if org:
        if current_user.is_organization_member(org.id):
            current_user.organizations.remove(org)
            db.session.commit()
            flash("You left the organization successfully. ", "success")
    return redirect(url_for("organization_bp.get", organization_id=org_id))


@organization_bp.route("/members/<org_id>", methods=["GET"])
def members(org_id):
    """Returns the list of members of an organization."""
    org = Organization.query.filter(Organization.id == org_id).first()
    if org:
        return render_template(
            "organization_members.html",
            organization=org,
            members=sorted(org.users, key=lambda user: user.last_seen, reverse=True),
        )
    return redirect(url_for("organization_bp.get", organization_id=org_id))

mosp/views/schema.py
import ast
import functools
import json
import operator
from typing import Dict
from typing import List
from urllib.parse import urljoin

from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import Response
from flask import url_for
from flask_babel import gettext
from flask_login import current_user
from flask_login import login_required
from flask_paginate import get_page_args
from flask_paginate import Pagination
from sqlalchemy import Boolean
from sqlalchemy import desc
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import nullslast
from sqlalchemy import or_

from mosp.bootstrap import application
from mosp.bootstrap import db
from mosp.forms import SchemaForm
from mosp.models import Event
from mosp.models import JsonObject
from mosp.models import Schema

schema_bp = Blueprint("schema_bp", __name__, url_prefix="/schema")
schemas_bp = Blueprint("schemas_bp", __name__, url_prefix="/schemas")


@schemas_bp.route("/", methods=["GET"])
def list_schemas():
    """Return the page which will display the list of schemas."""
    # Order by schema wich validates the most JSON objects.
    hot_schemas = (
        db.session.query(
            JsonObject.schema_id, func.count("*").label("JsonObject_count")
        )
        .group_by(JsonObject.schema_id)
        .subquery()
    )
    schemas = (
        db.session.query(Schema)
        .outerjoin(hot_schemas, (Schema.id == hot_schemas.c.schema_id))
        .order_by(nullslast(desc(hot_schemas.c.JsonObject_count)))
    )
    return render_template("schemas.html", schemas=schemas)


@schema_bp.route("/<int:schema_id>", defaults={"per_page": "20"}, methods=["GET"])
def get(per_page, schema_id=None):
    """Return the schema given in parameter with the objects validated by this
    schema. Also returns the objects validated by this schema. It is possible
    to filter the objects based on some properties of the schema.
    """
    schema = Schema.query.filter(Schema.id == schema_id).first()
    if schema is None:
        abort(404)

    # Log the event
    new_event = Event(
        scope="Schema",
        subject=f"id={schema_id}",
        action="schema_bp.get:GET",
        initiator=request.headers.get("User-Agent"),
    )
    db.session.add(new_event)
    db.session.commit()

    # Loads all objects related to the schema
    query = JsonObject.query.filter(JsonObject.schema_id == schema.id)

    # Search on the fields of the JSONB object
    # 1. Look for the searchable properties of the current schema. Actuallay we
    # accept string, boolean and integer
    search_keys = {
        key: (
            key in schema.json_schema["required"],
            schema.json_schema["properties"][key].get("type", False),
        )
        for key in schema.json_schema.get("properties", [])
        if schema.json_schema["properties"][key].get("type", False)
        in ["string", "boolean", "integer"]
    }
    # 2. Get the query of the user
    search_key = request.args.get("search_key", "")
    search_term = request.args.get("search_term", "")
    # 3. Prepare the filter (query on a JSONB object)  based on the type of the
    # attribute
    if search_key and search_term:
        if search_keys[search_key][1] == "string":
            # string: ilike search
            query = query.filter(
                JsonObject.json_object[(search_key)].astext.ilike(
                    "%" + search_term + "%"
                )
            )
        elif search_keys[search_key][1] == "boolean":
            # boolean
            query = query.filter(
                JsonObject.json_object[(search_key)]
                .astext.cast(Boolean)
                .is_(ast.literal_eval(search_term))
            )
        elif search_keys[search_key][1] == "integer":
            # integer
            query = query.filter(
                JsonObject.json_object[(search_key)].astext.cast(Integer)
                == ast.literal_eval(search_term)
            )

    # Pagination
    page, per_page, offset = get_page_args()
    pagination = Pagination(
        page=page,
        total=query.count(),
        css_framework="bootstrap4",
        search=False,
        record_name="objects",
        per_page=per_page,
    )

    return render_template(
        "schema.html",
        schema=schema,
        objects=query.offset(offset).limit(per_page),
        pagination=pagination,
        search_keys=search_keys,
        search_key=search_key,
        search_term=search_term,
    )


@schema_bp.route("/view/<int:schema_id>", methods=["GET"])
def view(schema_id=None):
    """
    Display the JSON part of a Schema object and some related informations.
    """
    json_schema = Schema.query.filter(Schema.id == schema_id).first()
    if json_schema is None:
        abort(404)
    result = json.dumps(
        json_schema.json_schema, sort_keys=True, indent=4, separators=(",", ": ")
    )
    return render_template(
        "view_schema.html", json_schema=json_schema, json_schema_pretty=result
    )


@schema_bp.route("/def/<int:schema_id>", methods=["GET"])
@schema_bp.route("/def/<uuid:schema_uuid>", methods=["GET"])
def definition(schema_id=None, schema_uuid=None):
    """
    Returns the defintion of a JSON schema (text/plain).
    """
    schema_uuid_absolute = urljoin(
        application.config["INSTANCE_URL"], "schema/def/" + str(schema_uuid)
    )
    json_schema = Schema.query.filter(
        or_(
            Schema.id == schema_id,
            Schema.json_schema[("$id")].astext == schema_uuid_absolute,
        )
    ).first()
    if json_schema is None:
        abort(404)
    result = json.dumps(
        json_schema.json_schema, sort_keys=True, indent=4, separators=(",", ": ")
    )
    return Response(result, mimetype="text/plain")


@schema_bp.route("/relations/<int:schema_id>", methods=["GET"])
def relations(schema_id=None, schema_uuid=None):
    """
    Display the relations of a Schema.
    """
    json_schema = Schema.query.filter(Schema.id == schema_id).first()
    if json_schema is None:
        abort(404)
    result = json.dumps(
        json_schema.json_schema, sort_keys=True, indent=4, separators=(",", ": ")
    )
    return render_template(
        "relations_schema.html", json_schema=json_schema, json_schema_pretty=result
    )


@schema_bp.route("/<int:schema_id>/get_objects", methods=["GET"])
def get_objects(schema_id=None):
    """Returns all JSON objects (JsonObject.json_object) validated by the
    JSON schema.
    """
    json_schema = Schema.query.filter(Schema.id == schema_id).first()
    if json_schema is None:
        abort(404)
    # Get all JSON objects (JsonObject.json_object) validated by this schema
    json_objects = [
        elem.json_object if isinstance(elem.json_object, list) else [elem.json_object]
        for elem in json_schema.objects
    ]
    # Flatten the list json_objects
    flat_json_objects: List[Dict] = functools.reduce(operator.iconcat, json_objects, [])
    # Prepare the result
    result = json.dumps(
        flat_json_objects, sort_keys=True, indent=4, separators=(",", ": ")
    )
    return Response(
        result,
        mimetype="application/json",
        headers={
            "Content-Disposition": "attachment;filename={}.json".format(
                json_schema.name.replace(" ", "_")
            )
        },
    )


@schema_bp.route("/create", methods=["GET"])
@schema_bp.route("/edit/<int:schema_id>", methods=["GET"])
@login_required
def form(schema_id=None, org_id=None):
    """Returns a form in order to edit a schema."""
    action = gettext("Create a schema")
    head_titles = [action]

    form = SchemaForm()
    form.org_id.choices = [(0, "")]
    form.org_id.choices.extend(
        [(org.id, org.name) for org in current_user.organizations]
    )

    if schema_id is None:
        # Creation of a new schema

        # initialization of the minimum for a valid JSON schema with an ID on
        # this platform.
        default_minimum_json_schema = {
            "id": "{}".format(
                urljoin(
                    application.config["INSTANCE_URL"],
                    "schema/def/<UUID-of-the-schema>",
                )
            ),
            "$schema": "http://json-schema.org/schema#",
            "title": "Title of the schema",
            "description": "Description of the purpose of this schema.",
            "type": "object",
            "properties": {},
            "required": [],
        }
        form.json_schema.data = json.dumps(
            default_minimum_json_schema,
            sort_keys=True,
            indent=4,
            separators=(",", ": "),
        )
        # set the organization id
        org_id = request.args.get("org_id", None)
        if org_id is not None:
            form.org_id.data = int(org_id)
        return render_template(
            "edit_schema.html",
            action=action,
            head_titles=head_titles,
            form=form,
            schema_id=schema_id,
        )

    # Edition of an existing schema
    schema = Schema.query.filter(Schema.id == schema_id).first()
    form = SchemaForm(obj=schema)
    form.json_schema.data = json.dumps(
        schema.json_schema, sort_keys=True, indent=4, separators=(",", ": ")
    )
    form.org_id.choices = [(0, "")]
    form.org_id.choices.extend(
        [(org.id, org.name) for org in current_user.organizations]
    )
    action = gettext("Edit a schema")
    head_titles = [action]
    head_titles.append(schema.name)
    return render_template(
        "edit_schema.html",
        action=action,
        head_titles=head_titles,
        schema=schema,
        form=form,
        schema_id=schema_id,
    )


@schema_bp.route("/create", methods=["POST"])
@schema_bp.route("/edit/<int:schema_id>", methods=["POST"])
@login_required
def process_form(schema_id=None):

mosp/templates/account_recovery_set_password.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h2>Enter your new password</h2>
            <form action="" method="POST" name="accountrecoveryform" id="accountrecoveryform">
                {{ form.hidden_tag() }}
                {{ form.password1(class_="form-control", placeholder="Please enter your new password.") }} {% for error in form.password1.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
                <br />
                {{ form.password2(class_="form-control", placeholder="Please enter your new password.") }} {% for error in form.password2.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}
                &nbsp;<span class="text-muted">{{ _('Minimum 20 characters.') }}</span>
                <br />
                {{ form.submit(class_="btn btn-default") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

mosp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="MOSP - {{ _('Create, edit and share JSON objects') }}" />
  <link rel="author" type="text/plain"  href="{{ url_for('humans')  }}" />
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />
  <link href="{{ url_for("objects_atom") }}" rel="alternate" title="Recent objects published on MOSP" type="application/atom+xml" />
  <link href="{{ url_for("schemas_atom") }}" rel="alternate" title="Recent schemas published on MOSP" type="application/atom+xml" />
  <link href="{{ url_for("collections_atom") }}" rel="alternate" title="Recent collections published on MOSP" type="application/atom+xml" />
  <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" />
  {% block head_css %}
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/bootstrap-select/dist/css/bootstrap-select.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/@fortawesome/fontawesome-free/css/all.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/code-prettify/src/prettify.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/code-prettify/styles/sunburst.css') }}">
  {% endblock %}
  <script type="application/javascript">document.interestCohort = null;</script>
  <script src="{{ url_for('static', filename='npm_components/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/popper.js/dist/umd/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/datatables.net/js/dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/datatables.net-bs4/js/dataTables.bootstrap4.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/lodash/lodash.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/code-prettify/src/prettify.js') }}?skin=sunburst"></script>
  <script src="{{ url_for('static', filename='js/templates.js') }}"></script>
  <title>MOSP</title>
  {% endblock %}
</head>
{% block page_body %}
<body onload="PR.prettyPrint()">
  {% block main_menu %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-MOSP-blue">
    <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename='img/logo.png') }}" width="120px" alt="MONARC Objects Sharing Platform" title="MONARC Objects Sharing Platform" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% block menu_links %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto w-100 justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('schemas_bp.list_schemas') }}" title="Schemas">{{ _('Schemas') }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('organizations_bp.list_organizations') }}" title="Organizations">{{ _('Organizations') }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('collections_bp.list_collections') }}" title="Collections">{{ _('Collections') }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('stats_bp.index') }}" title="Stats">{{ _('Stats') }}</a>
        </li>
        {% if current_user.is_authenticated %}
        {% if current_user.is_admin %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cogs"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownAdmin">
            <a class="dropdown-item" href="{{ url_for('admin_bp.dashboard') }}" title="Dashboard">{{ _('Dashboard') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin_bp.list_users') }}" title="Users">{{ _('Users') }}</a>
            <a class="dropdown-item" href="{{ url_for('admin_bp.form_user') }}" title="Users">{{ _('Add user') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin_bp.list_organizations') }}" title="Organizations">{{ _('Organizations') }}</a>
            <a class="dropdown-item" href="{{ url_for('admin_bp.form_organization') }}" title="Organizations">{{ _('Add organization') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/admin">Expert mode</a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownUser">
            <span class="dropdown-item"><div class="text-muted">{{ _('Signed in as') }}</div><div class="font-weight-bold">{{ current_user.login }}</div></span>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('user_bp.form') }}" title="Profile">{{ _('Profile') }}</a>
            <a class="dropdown-item" href="{{ url_for('user_bp.schemas') }}" title="Schemas">{{ _('Schemas') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('logout') }}" title="Sign out">{{ _('Sign out') }}</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('login') }}" title="{{ _('Sign in') }}"><i class="fas fa-sign-in-alt"></i></a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% endblock %}
  </nav>
  {% endblock %}
  <div class="container alert-message">
    {% block messages %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <br />
    {% for category, message in messages %}
    <div class="alert alert-{{category}}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message | safe }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% endblock %}
  </div>
  <br />
  <div role="main">
    {% block content %}{% endblock %}
  </div>
  <br />
  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <a href="{{ url_for('about') }}">{{ _('About') }}</a>
          &nbsp;&nbsp;
          <a href="{{ url_for('help') }}">{{ _('Help') }}</a>
          &nbsp;&nbsp;
          <a href="{{ url_for('terms') }}">{{ _('Terms') }}</a>
        </div>
      </div>
    </div>
  </footer>
</body>
{% endblock %}
</html>

mosp/templates/user_schemas.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>{{ _('Welcome') }} {{ user.login }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>{{ _('You are a member since') }} {{ user.created_at | datetimeformat }}.</p>
            <p>{{ _('See the') }} <a href="{{ url_for('user_bp.get', login=user.login) }}">{{ _('objects') }}</a> {{ _('you already created.') }}</p>
            <p>{{ _('Create and share a new object with one of the') }} <a href="{{ url_for('schemas_bp.list_schemas') }}">{{ _('available schemas') }}</a> {{ _('on the platform') }}.</p>
        </div>
    </div>
    {% if user.organizations | count != 0 %}
    <div class="row">
        <div class="col-md-12">
            <br />
            <h2>{{ _('Schemas in my organizations') }}</h2>
            {% for org in current_user.organizations %}
                <h3><a href="{{ url_for('organization_bp.get', organization_name=org.name) }}">{{ org.name }}</a></h3>
                <ul>
                {% for schema in org.schemas %}
                    <li><a href="{{ url_for('schema_bp.get', schema_id=schema.id) }}">{{ schema.name }}</a> -
                        {{ _('validates') }} {{ schema.objects.count() }} {{ _('objects') }} -
                        <a href="{{ url_for('schema_bp.form', schema_id=schema.id) }}">{{ _('edit') }}</a>
                    </li>
                {% endfor %}
                <li style="list-style-type: none;"><a href="{{ url_for('schema_bp.form', org_id=org.id) }}"><i class="fa fa-plus" title="{{ _('Add a new schema in this organization') }}"></i></a></li>
                </ul>
            {% endfor  %}
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12">
            <b>{{ _('You are in no organization.') }}</b>
            <p>{{ _('You can contact the responsible of an') }} <a href="{{ url_for('organizations_bp.list_organizations') }}">{{ _('organization') }}</a> {{ _('or look for an') }} <a href="{{ url_for('organizations_bp.list_organizations', is_membership_restricted=0) }}">{{ _('organization with no membership restriction') }}</a>.</p>
            <p>{{ _('Being part of an organization is required in order to publish an object.') }}</p>
        </div>
    </div>
    {% endif %}
    {% if user.organizations.count != 0 %}
    <div class="row">
      <div class="col-md-12">
          <a href="{{ url_for('schema_bp.form') }}" class="btn btn-default">{{ _('Create a new schema') }}</a>
      </div>
    </div>
    {% endif %}
</div>
{% endblock %}

mosp/templates/view_schema.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <b>{{ _('Updated') }}</b>
        </div>
        <div class="col-md-10 text-justify">
            {{ json_schema.last_updated | datetime }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <br />
            <pre class="prettyprint"><code>{{ json_schema_pretty }}</code></pre>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}